amazingapp/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from amazingapp.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),

    path('blog/', include('blog.urls', namespace='blog')),

]

blog/urls.py
from django.urls import path

from .views import BlogDetail, BlogList

app_name = 'Blog'

urlpatterns = [
    path('<pk>/', BlogDetail.as_view(), name='detail'),
    path('', BlogList.as_view(), name='list'),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Blog(models.Model):
    title = models.CharField(max_length=254)
    content = models.TextField()
    created = models.TimeField(auto_now=False, auto_now_add=True)
    update = models.TimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})

amazingapp/views.py
from django.views.generic import TemplateView

from blog.models import Blog


class Home(TemplateView):
    model = None
    context_object_name = 'home'
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog'] = Blog.objects.all()

        return context

blog/views.py
from django.views.generic import ListView, DetailView

from blog.models import Blog


class BlogList(ListView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blog/list.html'


class BlogDetail(DetailView):
    model = Blog
    context_object_name = 'blog'
    template_name = 'blog/detail.html'
    count_hit = True

templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>amazing blog details </title>
</head>
<body>
    <div class="container">

      <h1>
  {{ blog.title }}</h1>

<br/>
<p>{{ blog.content }}</p>
<br/>
Comment\\\\
    </div>
</body>
</html>

templates/blog/list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Amazing blog</title>
</head>
<body>
    <div class="container">

{% for blog in blog %}<h3><a href="{{ obj.get_absolute_url }}">
  {{ blog.title }}</a></h3><br/>
{{ blog.content }}<hr/>
{% endfor %}
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Amazing Home</title>
</head>
<body>
<header id="header-wrap">
  <!-- Navbar Start -->
  <nav class="navbar navbar-expand-lg fixed-top scrolling-navbar indigo">
    <div class="container">
          <li class="nav-item">
            <a class="nav-link" href='{% url "home" %}'>
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href='{% url "blog:list" %}'>
              Blog
            </a>
          </li>
    </div>
  </nav>
</header>
<h1>Welcome Home</h1>
      <div class="container">

{% for blog in blog %}
<h3><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h3><br/>
<p>{{ blog.content }}</p><hr/>
{% endfor %}
      </div>

</body>
</html>